language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '4.4'
- '4.0'
- '0.6'
env:
  secure: DMSQy/f91+KEQfwQgtCGzN6BI1ES9+iBwGHqdnRtCec8nJHALxHFqkea+aGsns07TpT+BSPl5MAoYrUUfezNSKQJBw1mDxxcommwrmxrNb56Y68ep6xLsLXfMtPMlMllUpL9b86J+i6NfTW/C5b95mqmmMA++k07lp0orUh2OcE0yw9Lc0u/T+3bwE2Cn7u/Hxzjv7soadnWqCjKTlRUiPEv4ZvDMRkQCAaaDkrCXS1D9/Zqqf4a04II/oEy+cAqOfLaE/JIaqGaxPPMoPlE3x5M6dBlABTe3DKBxEv96kqKR4ZRe7kpJwwzGFMfkgvSzSPtPQrdY7tC6+ODNR/w4R3vFEDfiUxkJElmzQazy7g/8wNPEzOCuGkc+RCxXpTUQGVqR2DmQ/zxG6K3/EtPo+ziLDevGX8EvkcIZLuTWsw3pLEeVY/Nj90RU24+AbPppBpmrFAH6V5oT+ZdkRKllgohSkrhbz2emisgXn9JekQ3YO72yPhTQwBZE3wEsgrRm77t3ATYMDgkm/KhagnTwsR0tQHMFrkMQt3qrnnYzOmc1rcMnFSlvLY+P2JlyErFXPuIqThNKXKehqO6npY9/5Ci7WI778DF7z4ighnlVZoKKLuYzsptf2NQ8+NF2PtyaqHL5EFt5/OXnmdx6QtLMtuceI2uGMuqLeL7ZZQGlz8=
