language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '4.4'
- '4.0'
- '0.6'
env:
  secure: Ep69qB4ibG9MG3J1d1I4AB24JetcrWUycXoYngIc9Pmfg1Rc5yScDfpNqUa1v20yMatViMYII9Tyr1Hhp2V9phQgATdJkLcc9KgidYciNpgaXjV47PjgCcfJBBA4R4H1Jk88CrYLYdvCr50h61InP9MzzQi8pPOvA5d0UTSBqCDSSGo3ueya79yqBgDNRHt62ndWCZnyYYmduEBBB8GB+gzQ0u+ZEGKAIFQs5BRJyQhk+lUdbKEsyFcOye8qzzL0TSVMjb0LSsTlfPcV3Kbiv0Tum4PjzSX+4gM8XOSASa1RAf7BSnZ88PXJkGiKb+aiNeTCDS1G/LOEain6UDPkkx7B0GeKsL6XQUJZ6yT4YQPgwaLPfqvoL2ZCOMe4VC1+WBEDgL8x9PrEippirF2/4PTjBZuUk6/ERR7uX4hpbykAHvXgwpqMxrKhoTRBKLBTpUaSs3Ac86PW2K3ee1p09Y44iv6z4mGPAUqWgYob76BypPeHG+7Y+1FrGwGVX16i6xYWRUIdmzyJ3fK+S+0yQrNnaZ50E/kb4Euvm/JdVOWsQClJ/ut0KHjBszYL61XMaR6hSS+yhflISb3WIaAH5TE68l3krex9oWBGf9Yya0Kg4hYr1LJYHW4POC/tYzPZQKL8Jpcp15OJ9G8U5u1AMEYovgZMhfkzZ0IwJ1cgg/8=
