language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
- '4.4'
- '4.0'
- '0.6'
env:
  secure: nV3BWqDwZCJv8pZv3zBO/YiyHyAhN4E/qkVZkEGPo/aO0rUZTCHMgMfLQxdVnCQPf7F6ZjYLxN6hpav8P7/f8WNbdGYBh7cEUU8oR8yz6LFPw/+x66a2XQMUl8G78yxd6QimtBrQXs986aNridtnOI9m+fpPO/VygI+BO+xbgfxWcguteJGRoIrmGc/L+hrhgSgZ97ZYtzL02tyqzKNT040od92/wZNYLKZdnYEWrMkubcfbbcw9dIm7GazOpcHepouwulCzcs5V+hNrsKfG8bVW2ip9X+XrwkSr7QvhzWZCRyvGJtbjpIDixsRdIy80bam172pz5BqnYPQyocZeDesgKOFG7vyIhomLd57WeG1wGrsY6qp2gluk8H5RI2qfhewtUtuiJKgY9XxV6Y5NfLfVYQFvNRJpR2hburfaC89p70gbFqceXfesER0QA1QfhjvCKlyP7n256TiM0cnx+etoI5NcW4QTO+KgQrnqdTHcbVi0mVnjXN1+aq30GaXPhWsDTSJqabkUfy4GzrR65iITbN2O0aGN3jE3CvgvCt4v2QX4vpDRN60H+PpdzhcZJW0v0HMlZmS054/dhqJb38J0t3I4Y+ITNdNSlm+yAN3FgeI5EaifLAW3h/tkB7WjivnBnb6C+fCmDng0ZYumtJW7zA7mbowK7DH0RmhmJwU=
